-- Generated from supabase/students_supabase.csv. Do not edit student rows here by hand.
insert into public.output_league_students (username, full_name, grade, class_name, group_name, is_teacher)
values
  ('anandiguastelli', 'Anandi Ricci Rodrigues Guastelli', 7, '7A', 'amarelo', false),
  ('brunosoares', 'Bruno Sayeg Soares', 7, '7A', 'branco', false),
  ('claragesteira', 'Clara Perez Gesteira', 7, '7A', 'branco', false),
  ('felipefreire', 'Felipe Faria Freire', 7, '7A', null, false),
  ('gabrielasouza', 'Gabriela Bastos De Souza', 7, '7A', 'branco', false),
  ('gianlucaalvarenga', 'Gianluca Zagui Alvarenga', 7, '7A', 'amarelo', false),
  ('gustavoalmendra', 'Gustavo Pardo Almendra', 7, '7A', 'amarelo', false),
  ('henriquegracio', 'Henrique De Castro Gracio', 7, '7A', 'branco', false),
  ('isabelacampos', 'Isabela Renda Campos', 7, '7A', 'amarelo', false),
  ('isabellasouza', 'Isabella Sannicola De Souza', 7, '7A', 'branco', false),
  ('joaomarinho', 'João Azevedo Marinho', 7, '7A', 'branco', false),
  ('joaoboscoli', 'João Pedro Ravagnani Boscoli', 7, '7A', 'amarelo', false),
  ('juliamourao', 'Julia Mendes Mourão', 7, '7A', 'branco', false),
  ('lauraakkari', 'Laura Antonini Akkari', 7, '7A', 'amarelo', false),
  ('luccasilva', 'Lucca Filizola Henrique Da Silva', 7, '7A', 'branco', false),
  ('luizabdo', 'Luiz Henrique Raffaelli Abdo', 7, '7A', 'amarelo', false),
  ('mariamoreira', 'Maria Eduarda Baroni Moreira', 7, '7A', 'branco', false),
  ('mariabraz', 'Maria Isabela Bussade Braz', 7, '7A', 'amarelo', false),
  ('mariaazenha', 'Maria Pia Sanches Azenha', 7, '7A', 'branco', false),
  ('matheusuejima', 'Matheus Jun Uejima', 7, '7A', 'branco', false),
  ('miguelmagalhaes', 'Miguel Edelweiss De Magalhães', 7, '7A', 'amarelo', false),
  ('maximofoletto', 'Máximo De Oliveira Foletto', 7, '7A', 'branco', false),
  ('oliviamoussalli', 'Olivia Chamma Moussalli', 7, '7A', 'amarelo', false),
  ('pedrokalili', 'Pedro Carvalho Kalili', 7, '7A', 'branco', false),
  ('rafaelpicolo', 'Rafael Ayello Moura Canhassi Picolo', 7, '7A', 'amarelo', false),
  ('sofiaantunes', 'Sofia Cavalcanti Antunes', 7, '7A', 'branco', false),
  ('theomontanari', 'Theo Groppo Montanari', 7, '7A', 'amarelo', false),
  ('valentinaseverini', 'Valentina Koehler Severini', 7, '7A', 'amarelo', false),
  ('aliciacid', 'Alicia Queiroz Cid', 7, '7B', 'branco', false),
  ('andrenogueira', 'André Mckenzie Nogueira', 7, '7B', 'amarelo', false),
  ('antoniettafreitas', 'Antonietta Zapparolli Rodrigues De Freitas', 7, '7B', 'branco', false),
  ('beatrizfrayha', 'Beatriz Nudelman Frayha', 7, '7B', null, false),
  ('bellamattei', 'Bella Alvarez Mattei', 7, '7B', 'branco', false),
  ('bernardooliveira', 'Bernardo Lima Hyppolito Oliveira', 7, '7B', 'amarelo', false),
  ('carolinaloureiro', 'Carolina Licio Trigo De Loureiro', 7, '7B', 'branco', false),
  ('ceciliasantos', 'Cecilia Gonçalves Pupo Santos', 7, '7B', 'branco', false),
  ('claratranjan', 'Clara Emsenhuber Tranjan', 7, '7B', 'amarelo', false),
  ('gabrielgama', 'Gabriel Arantes Taveira Da Gama', 7, '7B', 'amarelo', false),
  ('gabriellastamato', 'Gabriella Reis Stamato', 7, '7B', 'amarelo', false),
  ('guilhermemarangoni', 'Guilherme Jafet Marangoni', 7, '7B', 'branco', false),
  ('helenafrayha', 'Helena Teodoro Frayha', 7, '7B', 'amarelo', false),
  ('henriquemelo', 'Henrique De Marca Filgueiras De Melo', 7, '7B', 'amarelo', false),
  ('joseborges', 'José Maia Borges', 7, '7B', 'amarelo', false),
  ('joaoabutara', 'João Paulo Resende Abutara', 7, '7B', 'amarelo', false),
  ('joaogoto', 'João Paulo Rodrigues Da Cunha Goto', 7, '7B', 'branco', false),
  ('leonardobarone', 'Leonardo Murrer Barone', 7, '7B', 'branco', false),
  ('lucasmayer', 'Lucas Carvalho Mayer', 7, '7B', 'branco', false),
  ('luisayunes', 'Luisa Koelle Yunes', 7, '7B', 'amarelo', false),
  ('luizmanssur', 'Luiz Felipe Zanchet Manssur', 7, '7B', 'amarelo', false),
  ('marcellajafet', 'Marcella Saad Jafet', 7, '7B', 'branco', false),
  ('mariaferraz', 'Maria Luisa Gomes Ferraz', 7, '7B', 'branco', false),
  ('mariafioravanti', 'Maria Luiza Marques Fioravanti', 7, '7B', null, false),
  ('martinribeiro', 'Martin Bresser Pereira De Oliveira Ribeiro', 7, '7B', 'branco', false),
  ('martinanegrini', 'Martina Beneduzzi Corsi Negrini', 7, '7B', 'amarelo', false),
  ('oliviafeneberg', 'Olivia Tavares Feneberg', 7, '7B', 'branco', false),
  ('pedrodiniz', 'Pedro Martins Diniz', 7, '7B', 'branco', false),
  ('pietrafarias', 'Pietra Porto De Farias', 7, '7B', 'amarelo', false),
  ('sophiaguerreiro', 'Sophia Medeiros Guerreiro', 7, '7B', 'branco', false),
  ('valentinacais', 'Valentina Billi Cais', 7, '7B', 'amarelo', false),
  ('alicegesteira', 'Alice Perez Gesteira', 7, '7C', 'branco', false),
  ('anahaddad', 'Ana Luiza Zwaretch Haddad', 7, '7C', 'amarelo', false),
  ('andrealves', 'André Carneiro Alves', 7, '7C', 'branco', false),
  ('antonioceravolo', 'Antonio Sant''Anna Ceravolo', 7, '7C', 'amarelo', false),
  ('beatrizsaad', 'Beatriz Bianchini Saad', 7, '7C', 'amarelo', false),
  ('bernardomontenegro', 'Bernardo De Morais Benassi Montenegro', 7, '7C', 'branco', false),
  ('camilaavian', 'Camila Rodrigues Avian', 7, '7C', 'amarelo', false),
  ('carolinagusmao', 'Carolina Arantes De Gusmão', 7, '7C', 'branco', false),
  ('ceciliaricciardi', 'Cecília Tena Garcia Ricciardi', 7, '7C', 'amarelo', false),
  ('eduardodedivitis', 'Eduardo Dedivitis', 7, '7C', 'branco', false),
  ('francescodippolito', 'Francesco Matta D''Ippolito', 7, '7C', 'branco', false),
  ('gabrielamartinez', 'Gabriela Thomé Nazar Martinez', 7, '7C', 'amarelo', false),
  ('georgeabissamra', 'George Fletcher Abissamra', 7, '7C', 'branco', false),
  ('giovannafigueiredo', 'Giovanna Montezano Figueiredo', 7, '7C', 'amarelo', false),
  ('guilhermesouza', 'Guilherme Bastos De Souza', 7, '7C', 'amarelo', false),
  ('isabelarocha', 'Isabela Menin Rocha', 7, '7C', 'amarelo', false),
  ('isabellamiceli', 'Isabella Olm Miceli', 7, '7C', 'branco', false),
  ('lorenzonascimento', 'Lorenzo Fernandes Melo Gato Do Nascimento', 7, '7C', 'amarelo', false),
  ('manuelacassins', 'Manuela Lebrão Cassins', 7, '7C', 'branco', false),
  ('manuelamedici', 'Manuela Paim Medici', 7, '7C', 'amarelo', false),
  ('marialobao', 'Maria Antonia Capanema Lobão', 7, '7C', null, false),
  ('michelmaalouli', 'Michel Khouri Maalouli', 7, '7C', null, false),
  ('oliviabarone', 'Olivia Sciallis Barone', 7, '7C', 'branco', false),
  ('rafaelmaluhy', 'Rafael Gutierrez Maluhy', 7, '7C', 'amarelo', false),
  ('rafaeldiomelli', 'Rafael Riedel Diomelli', 7, '7C', 'branco', false),
  ('stefanocarotta', 'Stefano Keimich Carotta', 7, '7C', 'amarelo', false),
  ('terezadias', 'Tereza Simioni De Carvalho Dias', 7, '7C', 'branco', false),
  ('theocalfat', 'Theo Pimenta Bueno Mattar Calfat', 7, '7C', 'branco', false),
  ('andreferrari', 'André Pinheiro Ferrari', 8, '8A', 'branco', false),
  ('antoniomello', 'Antonio Razuk Gomes De Mello', 8, '8A', 'branco', false),
  ('arthurrotta', 'Arthur Kovarsky Rotta', 8, '8A', 'amarelo', false),
  ('claraoliveira', 'Clara Fialho Oliveira', 8, '8A', 'amarelo', false),
  ('constanzaminders', 'Constanza Castilho De Nicola Minders', 8, '8A', 'amarelo', false),
  ('eduardogelailete', 'Eduardo Charbel Zreik Gelailete', 8, '8A', 'branco', false),
  ('felipedequech', 'Felipe Souza Naves Dequech', 8, '8A', 'branco', false),
  ('fernandamode', 'Fernanda De Souza Peixoto Modé', 8, '8A', 'amarelo', false),
  ('gabrielsaliba', 'Gabriel Faria Saliba', 8, '8A', 'amarelo', false),
  ('helenamarta', 'Helena Souto Dalla Marta', 8, '8A', 'branco', false),
  ('juliafranco', 'Júlia Berthoud Franco', 8, '8A', 'amarelo', false),
  ('liviacalife', 'Livia Moro Quinteiro Calife', 8, '8A', 'branco', false),
  ('lorenacyrino', 'Lorena Laia Cyrino', 8, '8A', 'branco', false),
  ('lorenzojoaquim', 'Lorenzo Madid Joaquim', 8, '8A', 'branco', false),
  ('luccavaleriano', 'Lucca Brasolin Valeriano', 8, '8A', 'amarelo', false),
  ('lumamonteiro', 'Luma Deschamps Monteiro', 8, '8A', 'amarelo', false),
  ('manuelaprofili', 'Manuela Capote Valente Profili', 8, '8A', 'branco', false),
  ('manuelaferraz', 'Manuela Nunes Ferraz', 8, '8A', 'branco', false),
  ('mariamanssur', 'Maria Fernanda Zahr Manssur', 8, '8A', 'amarelo', false),
  ('martinatoscano', 'Martina Conde Motta Toscano', 8, '8A', 'branco', false),
  ('mateuspalma', 'Mateus Medeiros Palma', 8, '8A', 'amarelo', false),
  ('pedrolilla', 'Pedro Rothschild De Abreu Lilla', 8, '8A', 'amarelo', false),
  ('pedrotizon', 'Pedro Siqueira Tizon', 8, '8A', 'branco', false),
  ('theofleury', 'Theo Fang Fleury', 8, '8A', 'amarelo', false),
  ('theodorosayad', 'Theodoro Brandão Le Voci Sayad', 8, '8A', 'amarelo', false),
  ('valentinamaranhao', 'Valentina Padovan Mesquita Maranhão', 8, '8A', 'branco', false),
  ('victoryvart', 'Victor Tuneu Chauffert- Yvart', 8, '8A', 'amarelo', false),
  ('agathamartins', 'Agatha Cecília Galdino Martins', 8, '8B', 'branco', false),
  ('anatrofimoff', 'Ana Beatriz Lourenço Trofimoff', 8, '8B', 'amarelo', false),
  ('anneuejima', 'Anne Lye Uejima', 8, '8B', 'amarelo', false),
  ('carlosoliveira', 'Carlos Eduardo Martucci De Oliveira', 8, '8B', 'amarelo', false),
  ('cesarfreitas', 'César Lemos De Freitas', 8, '8B', 'amarelo', false),
  ('danielbensoussan', 'Daniel Cabral Bensoussan', 8, '8B', 'amarelo', false),
  ('eduardanascimento', 'Eduarda Mascarenhas Nascimento', 8, '8B', 'amarelo', false),
  ('emanuellesalomone', 'Emanuelle Schmidt Salomone', 8, '8B', 'branco', false),
  ('enzoguimaraes', 'Enzo Santos Guimarães', 8, '8B', 'branco', false),
  ('felipemichalua', 'Felipe Dib Michalua', 8, '8B', 'amarelo', false),
  ('filipposalgado', 'Filippo Fernandes Salgado', 8, '8B', 'branco', false),
  ('floraamaral', 'Flora Siqueira Amaral', 8, '8B', 'amarelo', false),
  ('gustavohanssen', 'Gustavo Giuliano Hanssen', 8, '8B', 'branco', false),
  ('helenamarzo', 'Helena Carrazza Di Marzo', 8, '8B', 'branco', false),
  ('helenahasegawa', 'Helena Ferreira Hasegawa', 8, '8B', 'branco', false),
  ('isabellaoliveira', 'Isabella Martucci De Oliveira', 8, '8B', 'branco', false),
  ('isabellagomes', 'Isabella Neiva Ferreira Gomes', 8, '8B', 'amarelo', false),
  ('isabellacaldeira', 'Isabella Ruman Mendes Caldeira', 8, '8B', 'amarelo', false),
  ('joaocosentino', 'João Luz Cosentino', 8, '8B', 'amarelo', false),
  ('joaokietzmann', 'João Victor Tavares Kietzmann', 8, '8B', 'branco', false),
  ('lorenamourao', 'Lorena Rey Ortiz Mourão', 8, '8B', 'branco', false),
  ('manuelasouza', 'Manuela Martins Souza', 8, '8B', 'branco', false),
  ('mariasantos', 'Maria Eduarda Sousa Carvalho Dos Santos', 8, '8B', 'amarelo', false),
  ('mariarampasso', 'Maria Luiza Montoan Rampasso', 8, '8B', 'amarelo', false),
  ('marianaleal', 'Mariana Radzyckyj Leal', 8, '8B', 'branco', false),
  ('pedroeirado', 'Pedro Atallah Arantes Eirado', 8, '8B', 'amarelo', false),
  ('rafaellarubini', 'Rafaella Machado Rubini', 8, '8B', 'branco', false),
  ('suzanawerneck', 'Suzana Diniz Junqueira Werneck', 8, '8B', 'branco', false),
  ('antoniocintra', 'Antonio Brasil Cintra', 8, '8C', 'amarelo', false),
  ('antonioalves', 'Antonio Carlos Rodrigues Cardoso Alves', 8, '8C', 'branco', false),
  ('carolinalazzarini', 'Carolina Daher Lazzarini', 8, '8C', 'amarelo', false),
  ('catarinaramos', 'Catarina Youssef Merhi Ramos', 8, '8C', 'branco', false),
  ('edercampos', 'Eder Sá Castanheira Campos', 8, '8C', 'branco', false),
  ('fellipelagoa', 'Fellipe Chammas Lagôa', 8, '8C', 'branco', false),
  ('gabrielbotelho', 'Gabriel Epprecht Arruda Botelho', 8, '8C', 'amarelo', false),
  ('gabrielaferreira', 'Gabriela Tuychi Assis Ferreira', 8, '8C', 'amarelo', false),
  ('gabrielladottore', 'Gabriella Tabacniks Del Dottore', 8, '8C', 'branco', false),
  ('giuliacesar', 'Giulia Badra Cesar', 8, '8C', 'branco', false),
  ('isabelaarena', 'Isabela Diniz Arena', 8, '8C', 'amarelo', false),
  ('isabelapaganotti', 'Isabela Domingues Paganotti', 8, '8C', 'amarelo', false),
  ('juliepace', 'Julie Ricci Pace', 8, '8C', 'amarelo', false),
  ('lauraaraujo', 'Laura Souza Lima Bayeux De Araujo', 8, '8C', 'branco', false),
  ('leonardolucchesi', 'Leonardo Koelle Lucchesi', 8, '8C', 'branco', false),
  ('leticiaiasi', 'Letícia Rafaldini Iasi', 8, '8C', 'amarelo', false),
  ('lorenzomariutti', 'Lorenzo Adm Mariutti', 8, '8C', 'branco', false),
  ('lucaquarta', 'Luca Indalecio Quarta', 8, '8C', 'branco', false),
  ('lucasgontijo', 'Lucas Melo De Souza Gontijo', 8, '8C', 'branco', false),
  ('lucasmaluf', 'Lucas Olivieri Maluf', 8, '8C', 'amarelo', false),
  ('luccamarsiarelli', 'Lucca Cervoni Marsiarelli', 8, '8C', 'amarelo', false),
  ('luiscardieri', 'Luis Henrique Pacheco Cardieri', 8, '8C', 'amarelo', false),
  ('manuelalozargo', 'Manuela Moralez Lozargo', 8, '8C', 'amarelo', false),
  ('mariahrochel', 'Mariah Ferrão Sant´Anna Yañez Rochel', 8, '8C', 'branco', false),
  ('miguelmarani', 'Miguel Dos Santos Marani', 8, '8C', 'amarelo', false),
  ('norahrosenthal', 'Norah Maksoud Rosenthal', 8, '8C', 'amarelo', false),
  ('rafaelahollo', 'Rafaela Pupo Hollo', 8, '8C', 'branco', false),
  ('rafaellaalves', 'Rafaella Garcia Ribeiro Alves', 8, '8C', 'branco', false),
  ('sophiasaraiva', 'Sophia Folchetti Saraiva', 8, '8C', 'branco', false),
  ('tomasyoneda', 'Tomás Pinheiro Guimarães Yoneda', 8, '8C', 'amarelo', false),
  ('victoriazakka', 'Victoria Haddad Zakka', 8, '8C', 'amarelo', false),
  ('yasminmonti', 'Yasmin Naomi Okayama Monti', 8, '8C', 'branco', false),
  ('anazancaner', 'Ana Beatriz Lerio Zancaner', 9, '9A', 'amarelo', false),
  ('anamascarenhas', 'Ana Luiza Netto Mascarenhas', 9, '9A', 'branco', false),
  ('anazimmermann', 'Ana Teresa Ferreira Da Rosa Zimmermann', 9, '9A', 'branco', false),
  ('antoniobiagi', 'Antonio Augusto Sandoval Biagi', 9, '9A', 'amarelo', false),
  ('aymanayache', 'Ayman Ayache', 9, '9A', 'amarelo', false),
  ('beatrizsantos', 'Beatriz Uliana Dos Santos', 9, '9A', 'amarelo', false),
  ('bernardomagalhaes', 'Bernardo Marcondes Magalhães', 9, '9A', 'amarelo', false),
  ('catarinamoreira', 'Catarina Sá Moreira', 9, '9A', 'branco', false),
  ('felipejardim', 'Felipe Duarte Jardim', 9, '9A', 'branco', false),
  ('felipeceneviva', 'Felipe Serra Ceneviva', 9, '9A', 'branco', false),
  ('gabrielszego', 'Gabriel Kenzo Sakai Szego', 9, '9A', 'branco', false),
  ('giuliapinto', 'Giulia Borghi Pinto', 9, '9A', 'branco', false),
  ('henriquemarsaioli', 'Henrique Botelho Marsaioli', 9, '9A', 'amarelo', false),
  ('isabelalogiodice', 'Isabela Manzini Logiodice', 9, '9A', 'amarelo', false),
  ('joaodedivitis', 'João Pedro Dedivitis', 9, '9A', 'amarelo', false),
  ('juliacastro', 'Julia O''Reilly De Araujo Castro', 9, '9A', 'amarelo', false),
  ('julietaribeiro', 'Julieta Bresser Pereira De Oliveira Ribeiro', 9, '9A', 'branco', false),
  ('lauramendonca', 'Laura Bellinato Mendonça', 9, '9A', 'amarelo', false),
  ('lorenacoffone', 'Lorena Hirsch Coffone', 9, '9A', 'amarelo', false),
  ('lorenzoviccari', 'Lorenzo Giacomazzi Viccari', 9, '9A', 'amarelo', false),
  ('manuelamoraes', 'Manuela Pekelman Levy Leite De Moraes', 9, '9A', 'amarelo', false),
  ('mariagomes', 'Maria Luiza Neiva Ferreira Gomes', 9, '9A', 'amarelo', false),
  ('marianavarella', 'Mariana Orlandi Varella', 9, '9A', 'amarelo', false),
  ('pedromurata', 'Pedro Barros Murata', 9, '9A', 'branco', false),
  ('rafaelandrade', 'Rafael Martin Soares De Andrade', 9, '9A', 'amarelo', false),
  ('raphaelsalerno', 'Raphael Bogus Salerno', 9, '9A', 'branco', false),
  ('anawerneck', 'Ana Beatriz Da Silva Werneck', 9, '9B', 'amarelo', false),
  ('catherinekassis', 'Catherine Ajaj Kassis', 9, '9B', 'amarelo', false),
  ('fernandasantos', 'Fernanda Uliana Dos Santos', 9, '9B', 'branco', false),
  ('guilhermeminders', 'Guilherme Castilho De Nicola Minders', 9, '9B', 'branco', false),
  ('henriquemovizzo', 'Henrique Arana Movizzo', 9, '9B', 'branco', false),
  ('henriquesilva', 'Henrique Junqueira De Freitas E Silva', 9, '9B', null, false),
  ('joaojereissati', 'Joao Pedro Gasparian Jereissati', 9, '9B', 'branco', false),
  ('joaquimcardoso', 'Joaquim Lehmkuhl Cardoso', 9, '9B', 'amarelo', false),
  ('joaomandur', 'João Pinheiro Esberard Mandur', 9, '9B', 'amarelo', false),
  ('lauramartins', 'Laura Merêncio Martins', 9, '9B', 'amarelo', false),
  ('lucabertocco', 'Luca Just Bertocco', 9, '9B', 'amarelo', false),
  ('manuelaamendoeira', 'Manuela Amendoeira', 9, '9B', 'branco', false),
  ('manuelatognotti', 'Manuela Tognotti', 9, '9B', 'branco', false),
  ('marcelovalente', 'Marcelo Mota Valente', 9, '9B', 'amarelo', false),
  ('mariacarneiro', 'Maria De Souza Carneiro', 9, '9B', 'branco', false),
  ('mariamachado', 'Maria Luiza Brandão Machado', 9, '9B', 'amarelo', false),
  ('matheuscarnevalli', 'Matheus Gazal Carnevalli', 9, '9B', 'branco', false),
  ('nicolaslopes', 'Nicolas Lopes', 9, '9B', 'amarelo', false),
  ('omarabissamra', 'Omar Fletcher Abissamra', 9, '9B', 'amarelo', false),
  ('rafaelmestieri', 'Rafael Braga Mestieri', 9, '9B', 'branco', false),
  ('rafaelagiacchetta', 'Rafaela Azzi Giacchetta', 9, '9B', 'amarelo', false),
  ('ricardonogueira', 'Ricardo Mckenzie Nogueira', 9, '9B', 'amarelo', false),
  ('robertalepiani', 'Roberta Barbieri Lepiani', 9, '9B', 'branco', false),
  ('saralima', 'Sara Ribeiro Dos Santos Lima', 9, '9B', 'branco', false),
  ('stelanahas', 'Stela Amaral Nahas', 9, '9B', 'branco', false),
  ('theopires', 'Theo Baracat Guedes Pires', 9, '9B', 'amarelo', false),
  ('tomasbranco', 'Tomás Vaccaro Castelo Branco', 9, '9B', 'branco', false),
  ('vitorgarofallo', 'Vitor Eduardo Bedotti Garofallo', 9, '9B', 'amarelo', false),
  ('alinesako', 'Aline Jacobini Sako', 9, '9C', 'branco', false),
  ('bernardozelazo', 'Bernardo David Zelazo', 9, '9C', 'branco', false),
  ('brunoalves', 'Bruno Valdemarin Alves', 9, '9C', 'amarelo', false),
  ('eduardoviegas', 'Eduardo Martins Vieira Viegas', 9, '9C', 'branco', false),
  ('eleonoratchalian', 'Eleonora Palenga Tchalian', 9, '9C', 'amarelo', false),
  ('fabiomattos', 'Fabio Dias Da Silva Nagliati Mattos', 9, '9C', 'branco', false),
  ('franciscoarantes', 'Francisco Teodoro Arantes', 9, '9C', 'amarelo', false),
  ('gabrielametzger', 'Gabriela Alonso Metzger', 9, '9C', 'amarelo', false),
  ('gabrielamarques', 'Gabriela Chevrier Marques', 9, '9C', 'branco', false),
  ('gabrielasantos', 'Gabriela Uliana Dos Santos', 9, '9C', 'branco', false),
  ('giancarloblumetti', 'Giancarlo Pinto Blumetti', 9, '9C', 'branco', false),
  ('joaoschlochauer', 'João Kohl Schlochauer', 9, '9C', 'branco', false),
  ('juliajereissati', 'Julia Gasparian Jereissati', 9, '9C', 'branco', false),
  ('julialeite', 'Julia Salles Leite', 9, '9C', null, false),
  ('leonardopinto', 'Leonardo Peres Goettert Pinto', 9, '9C', 'branco', false),
  ('lorenzoprado', 'Lorenzo Manini Prado', 9, '9C', 'amarelo', false),
  ('luistoscano', 'Luis Felipe Borges Berardo Toscano', 9, '9C', 'amarelo', false),
  ('marcelladomingues', 'Marcella Ferraro Domingues', 9, '9C', 'branco', false),
  ('matheusmaiorano', 'Matheus Panzan Maiorano', 9, '9C', 'amarelo', false),
  ('paolalarocca', 'Paola Prada Larocca', 9, '9C', 'branco', false),
  ('rodrigomaggioli', 'Rodrigo Maggioli', 9, '9C', 'branco', false),
  ('samiramani', 'Samira Mani', 9, '9C', 'amarelo', false),
  ('sophiaandrade', 'Sophia Valente Andrade', 9, '9C', 'branco', false),
  ('vickyxie', 'Vicky Zhuo Qi Xie', 9, '9C', 'amarelo', false),
  ('carolinaramos', 'Carolina De Oliveira Ramos', 9, '9D', 'branco', false),
  ('constanzacampofiorito', 'Constanza Ferreira Campofiorito', 9, '9D', 'branco', false),
  ('elenaantiquera', 'Elena Massara Antiquera', 9, '9D', 'amarelo', false),
  ('felipefranklin', 'Felipe De Almeida Franklin', 9, '9D', 'amarelo', false),
  ('fredericomaligo', 'Frederico Vianna Maligo', 9, '9D', 'branco', false),
  ('gabrielacuram', 'Gabriela Mello Curam', 9, '9D', 'branco', false),
  ('gianlucabarone', 'Gianluca Sciallis Barone', 9, '9D', 'branco', false),
  ('guilhermelitwin', 'Guilherme Moraes Stolf Litwin', 9, '9D', 'amarelo', false),
  ('gustavocheli', 'Gustavo Velasco Oliveira Cheli', 9, '9D', 'amarelo', false),
  ('henriquesantos', 'Henrique Gomes Dos Santos', 9, '9D', 'branco', false),
  ('isabellajafet', 'Isabella Saad Jafet', 9, '9D', 'branco', false),
  ('joaquimrosa', 'Joaquim Soto Garcia Rosa', 9, '9D', 'amarelo', false),
  ('joaoronzella', 'João Taddei Ronzella', 9, '9D', 'branco', false),
  ('larasarhan', 'Lara Boscardin Sarhan', 9, '9D', 'amarelo', false),
  ('luizapato', 'Luiza Bresser Pato', 9, '9D', 'branco', false),
  ('manuelaloureiro', 'Manuela Licio Trigo De Loureiro', 9, '9D', 'amarelo', false),
  ('mariaveloso', 'Maria Beatriz Pinto Veloso', 9, '9D', 'amarelo', false),
  ('miguelcoxo', 'Miguel Figueiredo Baldaia Coxo', 9, '9D', 'branco', false),
  ('oliviamanssur', 'Olivia Zanchet Manssur', 9, '9D', 'branco', false),
  ('patriciapierotti', 'Patricia Vianna Pierotti', 9, '9D', 'branco', false),
  ('patrickcollard', 'Patrick Martino Collard', 9, '9D', 'branco', false),
  ('rafaelcampos', 'Rafael Renda Campos', 9, '9D', 'amarelo', false),
  ('rodrigoszlejf', 'Rodrigo Szlejf', 9, '9D', 'amarelo', false),
  ('stellaazzi', 'Stella Paranhos Azzi', 9, '9D', 'amarelo', false),
  ('leleomaker', 'Leo Maker', 7, 'STAFF', null, true),
  ('leleomaker', 'Leo Maker', 8, 'STAFF', null, true),
  ('leleomaker', 'Leo Maker', 9, 'STAFF', null, true),
  ('davimaker', 'Davi Maker', 7, 'STAFF', null, true),
  ('davimaker', 'Davi Maker', 8, 'STAFF', null, true),
  ('davimaker', 'Davi Maker', 9, 'STAFF', null, true),
  ('brianmaker', 'Brian Maker', 7, 'STAFF', null, true),
  ('brianmaker', 'Brian Maker', 8, 'STAFF', null, true),
  ('brianmaker', 'Brian Maker', 9, 'STAFF', null, true)
on conflict (username, grade) do update set
  full_name = excluded.full_name,
  class_name = excluded.class_name,
  group_name = excluded.group_name,
  is_teacher = excluded.is_teacher;
