import { AudioLines, Sparkles, Volume2, VolumeX } from 'lucide-react';
import type { Settings as SettingsValue } from '../data/storage';
import Modal from './Modal';
import { paints, trails, decals, pitches } from '../data/garage';
export default function Settings({ value, onChange, onClose }: { value: SettingsValue; onChange: (s: SettingsValue) => void; onClose: () => void }) {
  const paint = paints.find(p => p.id === value.paint)!; const trail = trails.find(p => p.id === value.trail)!;
  return <Modal label="Settings" onClose={onClose} className="settings-modal"><span className="eyebrow">MAKE YOURSELF AT HOME</span><h2>Settings</h2><p className="muted">Your arena. Your rhythm.</p>
    <section className="garage"><div className="garage-preview" style={{ '--car-paint': paint.color, '--trail-paint': trail.color } as React.CSSProperties}><span className="eyebrow">YOUR ROVER / 01</span><div className="preview-trail" /><svg viewBox="0 0 180 100" role="img" aria-label={`${paint.name} rover with ${value.decal} decal`}><rect x="39" y="13" width="31" height="14" rx="5" fill="#050f1d"/><rect x="109" y="13" width="31" height="14" rx="5" fill="#050f1d"/><rect x="39" y="75" width="31" height="14" rx="5" fill="#050f1d"/><rect x="109" y="75" width="31" height="14" rx="5" fill="#050f1d"/><rect x="31" y="23" width="120" height="54" rx="19" fill={paint.color} stroke="#c5f2ff" strokeWidth="2"/><rect x="63" y="29" width="52" height="41" rx="9" fill="#102b43"/><path d="M100 31H106Q114 31 114 40V59Q114 67 106 67H100Z" fill="#81cce3"/><rect x="27" y="16" width="9" height="67" rx="3" fill="#7198b2"/><path d="M141 30V41M141 59V70" stroke="#efffff" strokeWidth="5"/>{value.decal === 'crown' ? <path d="M72 40L80 49L85 39L90 49L98 40L94 60H76Z" fill="#ffd079"/> : value.decal === 'bolt' ? <path d="M88 33L75 53H85L79 67L99 45H87Z" fill="#fff3c7"/> : <path d="M70 43H99M70 56H99" stroke="#fff3c7" strokeWidth="5"/>}</svg><strong>{paint.name}</strong></div>
      <fieldset><legend>01 / PAINT</legend><div className="garage-swatches">{paints.map(p => <button key={p.id} aria-label={p.name} aria-pressed={value.paint === p.id} style={{ '--swatch': p.color } as React.CSSProperties} onClick={() => onChange({ ...value, paint: p.id })}><span />{p.name.split(' ')[0]}</button>)}</div></fieldset>
      <fieldset><legend>02 / ROOF DECAL</legend><div className="garage-options">{decals.map(decal => <button key={decal} aria-pressed={value.decal === decal} onClick={() => onChange({ ...value, decal })}>{decal === 'crown' ? '♛' : decal === 'bolt' ? 'ϟ' : 'Ⅱ'} {decal}</button>)}</div></fieldset>
      <fieldset><legend>03 / BOOST TRAIL</legend><div className="garage-options">{trails.map(t => <button key={t.id} aria-pressed={value.trail === t.id} style={{ color: t.color }} onClick={() => onChange({ ...value, trail: t.id })}>{t.name}</button>)}</div></fieldset>
      <fieldset><legend>04 / MATCH ATMOSPHERE</legend><div className="pitch-options">{pitches.map(p => <button className={`pitch-option pitch-${p.id}`} key={p.id} aria-pressed={value.pitch === p.id} onClick={() => onChange({ ...value, pitch: p.id })}><span /><strong>{p.name}</strong></button>)}</div><p className="garage-hint">{pitches.find(p => p.id === value.pitch)?.description} Atmosphere changes apply next match; your rover updates immediately.</p></fieldset>
    </section>
    <button className="setting-row" role="switch" aria-checked={value.sound} onClick={() => onChange({ ...value, sound: !value.sound })}><span className="setting-icon">{value.sound ? <Volume2 /> : <VolumeX />}</span><span><strong>Sound effects</strong><small>Kicks, boosts, and a well-earned goal.</small></span><span className={`switch ${value.sound ? 'on' : ''}`} /></button>
    <button className="setting-row" role="switch" aria-checked={value.reducedMotion} onClick={() => onChange({ ...value, reducedMotion: !value.reducedMotion })}><span className="setting-icon"><Sparkles /></span><span><strong>Reduce motion</strong><small>Less animation and camera movement.</small></span><span className={`switch ${value.reducedMotion ? 'on' : ''}`} /></button>
    <div className="quiet-note"><AudioLines size={17} /> No background music. Just you and the arena.</div><button className="primary-button" onClick={onClose}>BACK TO IT</button>
  </Modal>;
}
