create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  username text not null unique check (username = lower(username) and username ~ '^[a-z0-9]+$'),
  full_name text not null,
  grade smallint not null check (grade in (7, 8, 9)),
  class_name text not null,
  group_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.student_sessions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  token_hash bytea not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days')
);

create table if not exists public.student_settings (
  student_id bigint primary key references public.students(id) on delete cascade,
  settings jsonb not null default '{"sound":true,"reducedMotion":false,"paint":"azure","trail":"ion","decal":"crown","pitch":"shuffle"}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.student_progress (
  student_id bigint not null references public.students(id) on delete cascade,
  language text not null check (language in ('python', 'swift', 'csharp')),
  level_id smallint not null check (level_id between 1 and 8),
  best_score integer not null default 0 check (best_score >= 0),
  stars smallint not null default 0 check (stars between 0 and 3),
  complete boolean not null default false,
  attempts integer not null default 0 check (attempts >= 0),
  updated_at timestamptz not null default now(),
  primary key (student_id, language, level_id)
);

create index if not exists student_sessions_expiry_idx on public.student_sessions (expires_at);
create index if not exists student_progress_leaderboard_idx on public.student_progress (language, best_score desc);

alter table public.students enable row level security;
alter table public.student_sessions enable row level security;
alter table public.student_settings enable row level security;
alter table public.student_progress enable row level security;

revoke all on table public.students from anon, authenticated;
revoke all on table public.student_sessions from anon, authenticated;
revoke all on table public.student_settings from anon, authenticated;
revoke all on table public.student_progress from anon, authenticated;

create or replace function private.output_league_student_id(p_session_token uuid)
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select session.student_id
  from public.student_sessions as session
  where session.token_hash = extensions.digest(p_session_token::text, 'sha256')
    and session.expires_at > now()
  limit 1
$$;

create or replace function private.output_league_state(p_student_id bigint, p_session_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'token', p_session_token,
    'expires_at', session.expires_at,
    'student', jsonb_build_object(
      'id', student.id,
      'username', student.username,
      'full_name', student.full_name,
      'grade', student.grade,
      'class_name', student.class_name,
      'group_name', student.group_name
    ),
    'settings', coalesce(preferences.settings, '{"sound":true,"reducedMotion":false,"paint":"azure","trail":"ion","decal":"crown","pitch":"shuffle"}'::jsonb),
    'progress', coalesce((
      select jsonb_object_agg(progress.level_id::text, jsonb_build_object(
        'best_score', progress.best_score,
        'stars', progress.stars,
        'complete', progress.complete
      ))
      from public.student_progress as progress
      where progress.student_id = student.id
        and progress.language = case student.grade when 7 then 'python' when 8 then 'swift' else 'csharp' end
    ), '{}'::jsonb)
  )
  from public.students as student
  join public.student_sessions as session
    on session.student_id = student.id
   and session.token_hash = extensions.digest(p_session_token::text, 'sha256')
   and session.expires_at > now()
  left join public.student_settings as preferences on preferences.student_id = student.id
  where student.id = p_student_id
  limit 1
$$;

create or replace function public.login_student(p_username text, p_grade integer)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  found_student_id bigint;
  session_token uuid := extensions.gen_random_uuid();
begin
  select student.id into found_student_id
  from public.students as student
  where student.username = lower(regexp_replace(coalesce(p_username, ''), '[^a-zA-Z0-9]', '', 'g'))
    and student.grade = p_grade
  limit 1;

  if found_student_id is null then return null; end if;

  delete from public.student_sessions where expires_at <= now();
  insert into public.student_sessions (student_id, token_hash)
  values (found_student_id, extensions.digest(session_token::text, 'sha256'));
  insert into public.student_settings (student_id) values (found_student_id) on conflict (student_id) do nothing;

  return private.output_league_state(found_student_id, session_token);
end
$$;

create or replace function public.get_student_state(p_session_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare student_id bigint;
begin
  student_id := private.output_league_student_id(p_session_token);
  if student_id is null then return null; end if;
  return private.output_league_state(student_id, p_session_token);
end
$$;

create or replace function public.save_student_settings(p_session_token uuid, p_settings jsonb)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  student_id bigint;
  clean_settings jsonb;
begin
  student_id := private.output_league_student_id(p_session_token);
  if student_id is null then return false; end if;

  clean_settings := jsonb_build_object(
    'sound', case when jsonb_typeof(p_settings->'sound') = 'boolean' then (p_settings->>'sound')::boolean else true end,
    'reducedMotion', case when jsonb_typeof(p_settings->'reducedMotion') = 'boolean' then (p_settings->>'reducedMotion')::boolean else false end,
    'paint', case when p_settings->>'paint' in ('azure', 'coral', 'mint', 'violet') then p_settings->>'paint' else 'azure' end,
    'trail', case when p_settings->>'trail' in ('ion', 'solar', 'plasma') then p_settings->>'trail' else 'ion' end,
    'decal', case when p_settings->>'decal' in ('crown', 'stripes', 'bolt') then p_settings->>'decal' else 'crown' end,
    'pitch', case when p_settings->>'pitch' in ('shuffle', 'alpine', 'rain', 'ice', 'worn') then p_settings->>'pitch' else 'shuffle' end
  );

  insert into public.student_settings (student_id, settings, updated_at)
  values (student_id, clean_settings, now())
  on conflict (student_id) do update set settings = excluded.settings, updated_at = excluded.updated_at;
  return true;
end
$$;

create or replace function public.save_student_progress(p_session_token uuid, p_language text, p_level_id integer, p_score integer, p_stars integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  student_id bigint;
  student_grade smallint;
  expected_language text;
begin
  student_id := private.output_league_student_id(p_session_token);
  if student_id is null or p_level_id not between 1 and 8 or p_score < 0 or p_stars not between 0 and 3 then return false; end if;

  select grade into student_grade from public.students where id = student_id;
  expected_language := case student_grade when 7 then 'python' when 8 then 'swift' else 'csharp' end;
  if p_language <> expected_language then return false; end if;

  insert into public.student_progress (student_id, language, level_id, best_score, stars, complete, attempts, updated_at)
  values (student_id, p_language, p_level_id, p_score, p_stars, true, 1, now())
  on conflict (student_id, language, level_id) do update set
    best_score = greatest(public.student_progress.best_score, excluded.best_score),
    stars = greatest(public.student_progress.stars, excluded.stars),
    complete = true,
    attempts = public.student_progress.attempts + 1,
    updated_at = excluded.updated_at;
  return true;
end
$$;

create or replace function public.get_all_time_leaders()
returns table(language text, rank bigint, display_name text, total_score bigint, total_stars bigint, levels_completed bigint)
language sql
stable
security definer
set search_path = ''
as $$
  with totals as (
    select progress.language, progress.student_id, sum(progress.best_score)::bigint as total_score,
      sum(progress.stars)::bigint as total_stars, count(*) filter (where progress.complete)::bigint as levels_completed
    from public.student_progress as progress
    group by progress.language, progress.student_id
  ), ranked as (
    select totals.*, row_number() over (partition by totals.language order by totals.total_score desc, totals.total_stars desc, totals.student_id) as rank
    from totals
  )
  select ranked.language, ranked.rank,
    split_part(student.full_name, ' ', 1) || ' ' || left(regexp_replace(student.full_name, '^.*\s', ''), 1) || '.' as display_name,
    ranked.total_score, ranked.total_stars, ranked.levels_completed
  from ranked
  join public.students as student on student.id = ranked.student_id
  where ranked.rank <= 10
  order by ranked.language, ranked.rank
$$;

create or replace function public.logout_student(p_session_token uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.student_sessions where token_hash = extensions.digest(p_session_token::text, 'sha256');
  return found;
end
$$;

revoke all on function private.output_league_student_id(uuid) from public, anon, authenticated;
revoke all on function private.output_league_state(bigint, uuid) from public, anon, authenticated;
revoke all on function public.login_student(text, integer) from public, anon, authenticated;
revoke all on function public.get_student_state(uuid) from public, anon, authenticated;
revoke all on function public.save_student_settings(uuid, jsonb) from public, anon, authenticated;
revoke all on function public.save_student_progress(uuid, text, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.get_all_time_leaders() from public, anon, authenticated;
revoke all on function public.logout_student(uuid) from public, anon, authenticated;

grant execute on function public.login_student(text, integer) to anon, authenticated;
grant execute on function public.get_student_state(uuid) to anon, authenticated;
grant execute on function public.save_student_settings(uuid, jsonb) to anon, authenticated;
grant execute on function public.save_student_progress(uuid, text, integer, integer, integer) to anon, authenticated;
grant execute on function public.get_all_time_leaders() to anon, authenticated;
grant execute on function public.logout_student(uuid) to anon, authenticated;
